# Generated by Django 4.1 on 2023-05-01 17:01

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartela',
            name='responsavel',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bingo.pessoa', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='observacao',
            field=sloth.db.models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
