# Generated by Django 4.1 on 2023-05-02 08:42

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_cartela_realizou_pagamento_cartela_recebeu_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartela',
            name='posse',
            field=sloth.db.models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possecartela_set', to='bingo.pessoa', verbose_name='Posse'),
        ),
    ]
