# Generated by Django 4.1 on 2023-05-06 16:52

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_alter_cartela_posse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeioPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Meio de Pagamento',
                'verbose_name_plural': 'Meios de Pagamento',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.RemoveField(
            model_name='cartela',
            name='recebeu_comissao',
        ),
        migrations.AddField(
            model_name='cartela',
            name='comissao',
            field=sloth.db.models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Comissão'),
        ),
        migrations.AddField(
            model_name='evento',
            name='operadores',
            field=sloth.db.models.ManyToManyField(to='bingo.pessoa', verbose_name='Operadores'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=sloth.db.models.BrCpfField(blank=True, max_length=255, null=True, verbose_name='CPF'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'icon': 'person-check',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.AddField(
            model_name='cartela',
            name='meio_pagamento',
            field=sloth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bingo.meiopagamento', verbose_name='Meio de Pagamento'),
        ),
    ]
