# Generated by Django 4.1 on 2023-05-06 16:53

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0006_meiopagamento_remove_cartela_recebeu_comissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=sloth.db.models.BrRegionalPhoneField(blank=True, max_length=255, null=True, verbose_name='Telefone'),
        ),
    ]
